site_name: BENEFIT documentation
nav:
    - Home: index.md 
    
theme: readthedocs

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins: 
    - search
